<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <style>
    body{
        margin:50px 0 0 0;
        padding:0;
        width:100%;
        font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
        text-align:center;
        color:#aaa;
        font-size:18px;
    }
    h1{
        color:#719e40;
        letter-spacing:-3px;
        font-family:'Lato',sans-serif;
        font-size:100px;
        font-weight:200;
        margin-bottom:0;
    }
    </style>
</head>
<body>
    <h1>Slim</h1>
    <?php if(isset($name)) :?>
        <h2>Hello <?php echo htmlspecialchars($name); ?>!</h2>
<?php else: ?>
        <p>Try<a href="http://www.slimframework.com">Slim Framework</a></p>

        <?php echo $path; ?>
<?php endif; ?>

</body>
</html>